CREATE DATABASE IF NOT EXISTS cfw_db;
USE cfw_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    package_type ENUM('NORMAL', 'MEDIUM', 'SUPER') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 