services:
  - type: web
    name: flash-system
    env: node
    buildCommand: npm ci
    startCommand: node server.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: cfw_db
      - key: DB_PORT
        value: 3306
      - key: SESSION_SECRET
        sync: false 